var federals = {
  "Kuala Lumpur": {
    "Kepong": {},
    "Batu": {},
    "Wangsa Maju": {},
    "Bukit Bintang": {},
    "Lembah Pantai": {},
    "Seputeh": {},
    "Cheras": {},
    "Bandar Tun Razak": {},
  },
  "Kelantan": {"Ketereh": {}, "Tanah Merah": {}, "Pasir Puteh": {}, "Machang": {}, "Jeli": {}, "Kuala Krai": {}, "Gua Musang": {}},
  "Kedah": {
    "Langkawi": {},
    "Jerlun": {},
    "Kubang Pasu": {},
    "Padang Terap": {},
    "Pokok Sena": {},
    "Alor Setar": {},
    "Kuala Kedah": {},
    "Pendang": {},
    "Jerai": {},
    "Sik": {},
    "Merbok": {},
    "Sungai Petani": {},
    "Baling": {},
    "Padang Serai": {},
    "Kulim- Bandar Baharu": {},
    "Tumpat": {},
    "Pengkalan Chepa": {},
    "Kota Bharu": {},
    "Pasir Mas": {},
    "Rantau Panjang": {},
    "Kubang Kerian": {},
    "Bachok": {},
    "Ketereh": {},
    "Tanah Merah": {},
    "Pasir Puteh": {},
    "Machang": {},
    "Jeli": {},
    "Kuala Krai": {},
    "Gua Musang": {},
  },
  "Perlis": {"Padang Besar": {}, "Kangar": {}, "Arau": {}},
  "Labuan": {"Labuan": {}},
  "Putrajaya": {"Putrajaya": {}},
  "Johor": {
    "Segamat": {},
    "Sekijang": {},
    "Labis": {},
    "Pagoh": {},
    "Ledang": {},
    "Bakri": {},
    "Muar": {},
    "Parit Sulong": {},
    "Ayer Hitam": {},
    "Sri Gading": {},
    "Batu Pahat": {},
    "Simpang Renggam": {},
    "Kluang": {},
    "Sembrong": {},
    "Mersing": {},
    "Tenggara": {},
    "Kota Tinggi": {},
    "Pengerang": {},
    "Tebrau": {},
    "Pasir Gudang": {},
    "Johor Bahru": {},
    "Pulai": {},
    "Iskandar Puteri": {},
    "Kulai": {},
    "Pontian": {},
    "Tanjung Piai": {}
  },
  "Malacca": {"Masjid Tanah": {}, "Alor Gajah": {}, "Tangga Batu": {}, "Hang Tuah Jaya": {}, "Kota Melaka": {}, "Jasin": {}},
  "Negeri Sembilan": {"Jelebu": {}, "Jempol": {}, "Seremban": {}, "Kuala Pilah": {}, "Rasah": {}, "Rembau": {}, "Port": {}, "Tampin": {}},
  "Pahang": {
    "Cameron Highlands": {},
    "Lipis": {},
    "Raub": {},
    "Jerantut": {},
    "Indera Mahkota": {},
    "Kuantan": {},
    "Paya Besar": {},
    "Pekan": {},
    "Maran": {},
    "Kuala Krau": {},
    "Temerloh": {},
    "Bentong": {},
    "Bera": {},
    "Rompin": {}
  },
  "Penang": {
    "Kepala Batas": {},
    "Tasek Gelugor": {},
    "Bagan": {},
    "Permatang Pauh": {},
    "Bukit Mertajam": {},
    "Batu Kawan": {},
    "Nibong Tebal": {},
    "Bukit Bendera": {},
    "Tanjong": {},
    "Jelutong": {},
    "Bukit Gelugor": {},
    "Bayan Baru": {},
    "Balik Pulau": {}
  },
  "Perak": {
    "Gerik": {},
    "Lenggong": {},
    "Larut": {},
    "Parit Buntar": {},
    "Bagan Serai": {},
    "Bukit Gantang": {},
    "Taiping": {},
    "Padang Rengas": {},
    "Sungai Siput": {},
    "Tambun": {},
    "Ipoh Timor": {},
    "Ipoh Barat": {},
    "Batu Gajah": {},
    "Kuala Kangsar": {},
    "Beruas": {},
    "Parit": {},
    "Kampar": {},
    "Gopeng": {},
    "Tapah": {},
    "Pasir Salak": {},
    "Lumut": {},
    "Bagan Datuk": {},
    "Teluk Intan": {},
    "Tanjong Malim": {}
  },
  "Sabah": {
    "Kudat": {},
    "Kota Marudu": {},
    "Kota Belud": {},
    "Tuaran": {},
    "Sepanggar": {},
    "Kota Kinabalu": {},
    "Putatan": {},
    "Penampang": {},
    "Papar": {},
    "Kimanis": {},
    "Beaufort": {},
    "Sipitang": {},
    "Ranau": {},
    "Keningau": {},
    "Tenom": {},
    "Pensiangan": {},
    "Beluran": {},
    "Libaran": {},
    "Batu Sapi": {},
    "Sandakan": {},
    "Kinabatangan": {},
    "Lahad Datu": {},
    "Semporna": {},
    "Tawau": {},
    "Kalabakan": {}
  },
  "Sarawak": {
    "Mas Gading": {},
    "Santubong": {},
    "Petra Jaya": {},
    "Bandar Kuching": {},
    "Stampin": {},
    "Kota Samarahan": {},
    "Puncak Borneo": {},
    "Serian": {},
    "Batang Sadong": {},
    "Batang Lupar": {},
    "Sri Aman": {},
    "Lubok Antu": {},
    "Betong": {},
    "Saratok": {},
    "Tanjong Manis": {},
    "Igan": {},
    "Sarikei": {},
    "Julau": {},
    "Kanowit": {},
    "Lanang": {},
    "Sibu": {},
    "Mukah": {},
    "Selangau": {},
    "Kapit": {},
    "Hulu Rajang": {},
    "Bintulu": {},
    "Sibuti": {},
    "Miri": {},
    "Baram": {},
    "Limbang": {},
    "Lawas": {}
  },
  "Selangor": {
    "Sabak Bernam": {},
    "Sungai Besar": {},
    "Hulu Selangor": {},
    "Tanjong Karang": {},
    "Kuala Selangor": {},
    "Selayang": {},
    "Gombak": {},
    "Ampang": {},
    "Pandan": {},
    "Hulu Langat": {},
    "Bangi": {},
    "Puchong": {},
    "Subang": {},
    "Petaling Jaya": {},
    "Damansara": {},
    "Sungai Buloh": {},
    "Shah Alam": {},
    "Kapar": {},
    "Klang": {},
    "Kota Raja": {},
    "Kuala Langat": {},
    "Sepang": {}
  },
  "Terengganu": {
    "Besut": {},
    "Setiu": {},
    "Kuala Nerus": {},
    "Kuala Terengganu": {},
    "Marang": {},
    "Hulu Terengganu": {},
    "Dungun": {},
    "Kemaman": {}
  }
};
