var s = [
  {"region": "Perlis", "federal": "Padang Besar", "state": "Titi Tinggi"},
  {"region": "Perlis", "federal": "Padang Besar", "state": "Beseri"},
  {"region": "Perlis", "federal": "Padang Besar", "state": "Chuping"},
  {"region": "Perlis", "federal": "Padang Besar", "state": "Mata Ayer"},
  {"region": "Perlis", "federal": "Padang Besar", "state": "Santan"},
  {"region": "Perlis", "federal": "Kangar", "state": "Bintong"},
  {"region": "Perlis", "federal": "Kangar", "state": "Sena"},
  {"region": "Perlis", "federal": "Kangar", "state": "Indera Kayangan"},
  {"region": "Perlis", "federal": "Kangar", "state": "Kuala Perlis"},
  {"region": "Perlis", "federal": "Kangar", "state": "Kayang"},
  {"region": "Perlis", "federal": "Arau", "state": "Pauh"},
  {"region": "Perlis", "federal": "Arau", "state": "Tambun Tulang"},
  {"region": "Perlis", "federal": "Arau", "state": "Guar Sanji"},
  {"region": "Perlis", "federal": "Arau", "state": "Simpang Empat"},
  {"region": "Perlis", "federal": "Arau", "state": "Sanglang"},
  {"region": "Kedah", "federal": "Langkawi", "state": "Ayer Hangat"},
  {"region": "Kedah", "federal": "Langkawi", "state": "Kuah"},
  {"region": "Kedah", "federal": "Jerlun", "state": "Kota Siputeh"},
  {"region": "Kedah", "federal": "Jerlun", "state": "Ayer Hitam"},
  {"region": "Kedah", "federal": "Kubang Pasu", "state": "Bukit Kayu Hitam"},
  {"region": "Kedah", "federal": "Kubang Pasu", "state": "Jitra"},
  {"region": "Kedah", "federal": "Padang Terap", "state": "Kuala Nerang"},
  {"region": "Kedah", "federal": "Padang Terap", "state": "Pedu"},
  {"region": "Kedah", "federal": "Pokok Sena", "state": "Bukit Lada"},
  {"region": "Kedah", "federal": "Pokok Sena", "state": "Bukit Pinang"},
  {"region": "Kedah", "federal": "Pokok Sena", "state": "Derga"},
  {"region": "Kedah", "federal": "Alor Setar", "state": "Suka Menanti"},
  {"region": "Kedah", "federal": "Alor Setar", "state": "Kota Darul Aman"},
  {"region": "Kedah", "federal": "Alor Setar", "state": "Alor Mengkudu"},
  {"region": "Kedah", "federal": "Kuala Kedah", "state": "Anak Bukit"},
  {"region": "Kedah", "federal": "Kuala Kedah", "state": "Kubang Rotan"},
  {"region": "Kedah", "federal": "Pendang", "state": "Tokai"},
  {"region": "Kedah", "federal": "Pendang", "state": "Sungai Tiang"},
  {"region": "Kedah", "federal": "Jerai", "state": "Sungai Limau"},
  {"region": "Kedah", "federal": "Jerai", "state": "Guar Chempedak"},
  {"region": "Kedah", "federal": "Jerai", "state": "Gurun"},
  {"region": "Kedah", "federal": "Sik", "state": "Belantek"},
  {"region": "Kedah", "federal": "Sik", "state": "Jeneri"},
  {"region": "Kedah", "federal": "Merbok", "state": "Bukit Selambau"},
  {"region": "Kedah", "federal": "Merbok", "state": "Tanjong Dawai"},
  {"region": "Kedah", "federal": "Sungai Petani", "state": "Pantai Merdeka"},
  {"region": "Kedah", "federal": "Sungai Petani", "state": "Bakar Arang"},
  {"region": "Kedah", "federal": "Sungai Petani", "state": "Sidam"},
  {"region": "Kedah", "federal": "Baling", "state": "Bayu"},
  {"region": "Kedah", "federal": "Baling", "state": "Kupang"},
  {"region": "Kedah", "federal": "Baling", "state": "Kuala Ketil"},
  {"region": "Kedah", "federal": "Padang Serai", "state": "Merbau Pulas"},
  {"region": "Kedah", "federal": "Padang Serai", "state": "Lunas"},
  {"region": "Kedah", "federal": "Kulim- Bandar Baharu", "state": "Kulim"},
  {"region": "Kedah", "federal": "Kulim- Bandar Baharu", "state": "Bandar Baharu"},
  {"region": "Kedah", "federal": "Tumpat", "state": " Pengkalan Kubor"},
  {"region": "Kedah", "federal": "Tumpat", "state": "&#9;Kelaboran"},
  {"region": "Kedah", "federal": "Tumpat", "state": "Pasir Pekan"},
  {"region": "Kedah", "federal": "Tumpat", "state": "Wakaf Bharu"},
  {"region": "Kedah", "federal": "Pengkalan&#9;Chepa", "state": "Kjang"},
  {"region": "Kedah", "federal": "Pengkalan&#9;Chepa", "state": "&#9;Chempaka"},
  {"region": "Kedah", "federal": "Pengkalan&#9;Chepa", "state": "&#9;Panchor"},
  {"region": "Kedah", "federal": "Kota Bharu", "state": "Tanjong Mas"},
  {"region": "Kedah", "federal": "Kota Bharu", "state": "Kota Lama"},
  {"region": "Kedah", "federal": "Kota Bharu", "state": "Bunut Payong"},
  {"region": "Kedah", "federal": "Pasir Mas", "state": "Tendong"},
  {"region": "Kedah", "federal": "Pasir Mas", "state": "Pengkalan Pasir"},
  {"region": "Kedah", "federal": "Pasir Mas", "state": "Meranti"},
  {"region": "Kedah", "federal": "Rantau Panjang", "state": "Chetok"},
  {"region": "Kedah", "federal": "Rantau Panjang", "state": "Gual Periok"},
  {"region": "Kedah", "federal": "Rantau Panjang", "state": "Apam Putra"},
  {"region": "Kedah", "federal": "Kubang Kerian", "state": "Salor"},
  {"region": "Kedah", "federal": "Kubang Kerian", "state": "Pasir Tumboh"},
  {"region": "Kedah", "federal": "Kubang Kerian", "state": "Demit"},
  {"region": "Kedah", "federal": "Bachok", "state": "Tawang", "undefined": "&#9;"},
  {"region": "Kedah", "federal": "Bachok", "state": "Pantai Irama"},
  {"region": "Kedah", "federal": "Bachok", "state": "Jelawat"},
  {"region": "Kelantan", "federal": "Ketereh", "state": "Melor"},
  {"region": "Kelantan", "federal": "Ketereh", "state": "Kadok"},
  {"region": "Kelantan", "federal": "Ketereh", "state": "Kok Lanas"},
  {"region": "Kelantan", "federal": "Tanah Merah", "state": "Bukit Panau"},
  {"region": "Kelantan", "federal": "Tanah Merah", "state": "Gual Ipoh"},
  {"region": "Kelantan", "federal": "Tanah Merah", "state": "Kemahang"},
  {"region": "Kelantan", "federal": "Pasir Puteh", "state": "Selising"},
  {"region": "Kelantan", "federal": "Pasir Puteh", "state": "Limbongan"},
  {"region": "Kelantan", "federal": "Pasir Puteh", "state": "Semerak"},
  {"region": "Kelantan", "federal": "Pasir Puteh", "state": "Gaal"},
  {"region": "Kelantan", "federal": "Machang", "state": "Pulai Chondong"},
  {"region": "Kelantan", "federal": "Machang", "state": "Temangan"},
  {"region": "Kelantan", "federal": "Machang", "state": "Kemuning"},
  {"region": "Kelantan", "federal": "Jeli", "state": "Bukit Bunga"},
  {"region": "Kelantan", "federal": "Jeli", "state": "Air Lanas"},
  {"region": "Kelantan", "federal": "Jeli", "state": "Kuala Balah"},
  {"region": "Kelantan", "federal": "Kuala Krai", "state": "Mengkebang"},
  {"region": "Kelantan", "federal": "Kuala Krai", "state": "Guchil"},
  {"region": "Kelantan", "federal": "Kuala Krai", "state": "Manek Urai"},
  {"region": "Kelantan", "federal": "Kuala Krai", "state": "Dabong"},
  {"region": "Kelantan", "federal": "Gua Musang", "state": "Nenggiri"},
  {"region": "Kelantan", "federal": "Gua Musang", "state": "Paloh"},
  {"region": "Kelantan", "federal": "Gua Musang", "state": "Galas"},
  {"region": "Terengganu", "federal": "Besut", "state": "Kuala Besut"},
  {"region": "Terengganu", "federal": "Besut", "state": "Kota Putera"},
  {"region": "Terengganu", "federal": "Besut", "state": "Jertih"},
  {"region": "Terengganu", "federal": "Besut", "state": "Hulu Besut"},
  {"region": "Terengganu", "federal": "Setiu", "state": "Jabi"},
  {"region": "Terengganu", "federal": "Setiu", "state": "Permaisuri"},
  {"region": "Terengganu", "federal": "Setiu", "state": "Langkap"},
  {"region": "Terengganu", "federal": "Setiu", "state": "Batu Rakit"},
  {"region": "Terengganu", "federal": "Kuala Nerus", "state": "Tepuh"},
  {"region": "Terengganu", "federal": "Kuala Nerus", "state": "Buluh Gading"},
  {"region": "Terengganu", "federal": "Kuala Nerus", "state": "Seberang Takir"},
  {"region": "Terengganu", "federal": "Kuala Nerus", "state": "Bukit Tunggal"},
  {"region": "Terengganu", "federal": "Kuala Terengganu", "state": "Wakaf Mempelam"},
  {"region": "Terengganu", "federal": "Kuala Terengganu", "state": "Bandar"},
  {"region": "Terengganu", "federal": "Kuala Terengganu", "state": "Ladang"},
  {"region": "Terengganu", "federal": "Kuala Terengganu", "state": "Batu Buruk"},
  {"region": "Terengganu", "federal": "Marang", "state": "Alur Limbat"},
  {"region": "Terengganu", "federal": "Marang", "state": "Bukit Payung"},
  {"region": "Terengganu", "federal": "Marang", "state": "Ru Rendang"},
  {"region": "Terengganu", "federal": "Marang", "state": "Pengkalan Berangan"},
  {"region": "Terengganu", "federal": "Hulu Terengganu", "state": "Telemung"},
  {"region": "Terengganu", "federal": "Hulu Terengganu", "state": "Manir"},
  {"region": "Terengganu", "federal": "Hulu Terengganu", "state": "Kuala Berang"},
  {"region": "Terengganu", "federal": "Hulu Terengganu", "state": "Ajil"},
  {"region": "Terengganu", "federal": "Dungun", "state": "Bukit Besi"},
  {"region": "Terengganu", "federal": "Dungun", "state": "Rantau Abang"},
  {"region": "Terengganu", "federal": "Dungun", "state": "Sura"},
  {"region": "Terengganu", "federal": "Dungun", "state": "Paka"},
  {"region": "Terengganu", "federal": "Kemaman", "state": "Kemasik"},
  {"region": "Terengganu", "federal": "Kemaman", "state": "Kijal"},
  {"region": "Terengganu", "federal": "Kemaman", "state": "Cukai"},
  {"region": "Terengganu", "federal": "Kemaman", "state": "Air Putih"},
  {"region": "Penang", "federal": "Kepala Batas", "state": "Penaga"},
  {"region": "Penang", "federal": "Kepala Batas", "state": "Bertam"},
  {"region": "Penang", "federal": "Kepala Batas", "state": "Pinang Tunggal"},
  {"region": "Penang", "federal": "Tasek Gelugor", "state": "Permatang Berangan"},
  {"region": "Penang", "federal": "Tasek Gelugor", "state": "Sungai Dua"},
  {"region": "Penang", "federal": "Tasek Gelugor", "state": "Telok Ayer Tawar"},
  {"region": "Penang", "federal": "Bagan", "state": "Sungai Puyu"},
  {"region": "Penang", "federal": "Bagan", "state": "Bagan Jermal"},
  {"region": "Penang", "federal": "Bagan", "state": "Bagan Dalam"},
  {"region": "Penang", "federal": "Permatang Pauh", "state": "Seberang Jaya"},
  {"region": "Penang", "federal": "Permatang Pauh", "state": "Permatang Pasir"},
  {"region": "Penang", "federal": "Permatang Pauh", "state": "Penanti"},
  {"region": "Penang", "federal": "Bukit Mertajam", "state": "Berapit"},
  {"region": "Penang", "federal": "Bukit Mertajam", "state": "Machang Bubuk"},
  {"region": "Penang", "federal": "Bukit Mertajam", "state": "Padang Lalang"},
  {"region": "Penang", "federal": "Batu Kawan", "state": "Perai"},
  {"region": "Penang", "federal": "Batu Kawan", "state": "Bukit Tengah"},
  {"region": "Penang", "federal": "Batu Kawan", "state": "Bukit Tambun"},
  {"region": "Penang", "federal": "Nibong Tebal", "state": "Jawi"},
  {"region": "Penang", "federal": "Nibong Tebal", "state": "Sungai Bakap"},
  {"region": "Penang", "federal": "Nibong Tebal", "state": "Sungai Acheh"},
  {"region": "Penang", "federal": "Bukit Bendera", "state": "Tanjong Bunga"},
  {"region": "Penang", "federal": "Bukit Bendera", "state": "Air Putih"},
  {"region": "Penang", "federal": "Bukit Bendera", "state": "Kebun Bunga"},
  {"region": "Penang", "federal": "Bukit Bendera", "state": "Pulau Tikus"},
  {"region": "Penang", "federal": "Tanjong", "state": "Padang Kota"},
  {"region": "Penang", "federal": "Tanjong", "state": "Pengkalan Kota"},
  {"region": "Penang", "federal": "Tanjong", "state": "Komtar"},
  {"region": "Penang", "federal": "Jelutong", "state": "Datok Keramat"},
  {"region": "Penang", "federal": "Jelutong", "state": "Sungai Pinang"},
  {"region": "Penang", "federal": "Jelutong", "state": "Batu Lancang"},
  {"region": "Penang", "federal": "Bukit Gelugor", "state": "Seri Delima"},
  {"region": "Penang", "federal": "Bukit Gelugor", "state": "Air Itam"},
  {"region": "Penang", "federal": "Bukit Gelugor", "state": "Paya Terubong"},
  {"region": "Penang", "federal": "Bayan Baru", "state": "Batu Uban"},
  {"region": "Penang", "federal": "Bayan Baru", "state": "Pantai Jerejak"},
  {"region": "Penang", "federal": "Bayan Baru", "state": "Batu Maung"},
  {"region": "Penang", "federal": "Balik Pulau", "state": "Bayan Lepas"},
  {"region": "Penang", "federal": "Balik Pulau", "state": "Pulau Betong"},
  {"region": "Penang", "federal": "Balik Pulau", "state": "Telok Bahang"},
  {"region": "Perak", "federal": "Gerik", "state": "Pengkalan Hulu"},
  {"region": "Perak", "federal": "Gerik", "state": "Temenggor"},
  {"region": "Perak", "federal": "Lenggong", "state": "Kenering"},
  {"region": "Perak", "federal": "Lenggong", "state": "Kota Tampan"},
  {"region": "Perak", "federal": "Larut", "state": "Selama"},
  {"region": "Perak", "federal": "Larut", "state": "Kubu Gajah"},
  {"region": "Perak", "federal": "Larut", "state": "Batu Kurau"},
  {"region": "Perak", "federal": "Parit Buntar", "state": "Titi Serong"},
  {"region": "Perak", "federal": "Parit Buntar", "state": "Kuala Kurau"},
  {"region": "Perak", "federal": "Bagan Serai", "state": "Alor Pongsu"},
  {"region": "Perak", "federal": "Bagan Serai", "state": "Gunong Semanggol"},
  {"region": "Perak", "federal": "Bagan Serai", "state": "Selinsing"},
  {"region": "Perak", "federal": "Bukit Gantang", "state": "Kuala Sepetang"},
  {"region": "Perak", "federal": "Bukit Gantang", "state": "Changkat Jering"},
  {"region": "Perak", "federal": "Bukit Gantang", "state": "Trong"},
  {"region": "Perak", "federal": "Taiping", "state": "Kamunting"},
  {"region": "Perak", "federal": "Taiping", "state": "Pokok Assam"},
  {"region": "Perak", "federal": "Taiping", "state": "Aulong"},
  {"region": "Perak", "federal": "Padang Rengas", "state": "Chenderoh"},
  {"region": "Perak", "federal": "Padang Rengas", "state": "Lubok Merbau"},
  {"region": "Perak", "federal": "Sungai Siput", "state": "Lintang"},
  {"region": "Perak", "federal": "Tambun", "state": "Manjoi"},
  {"region": "Perak", "federal": "Tambun", "state": "Hulu Kinta"},
  {"region": "Perak", "federal": "Ipoh Timor", "state": "Canning"},
  {"region": "Perak", "federal": "Ipoh Timor", "state": "Tebing Tinggi"},
  {"region": "Perak", "federal": "Ipoh Timor", "state": "Pasir Pinji"},
  {"region": "Perak", "federal": "Ipoh Barat", "state": "Bercham"},
  {"region": "Perak", "federal": "Ipoh Barat", "state": "Kepayang"},
  {"region": "Perak", "federal": "Ipoh Barat", "state": "Buntong"},
  {"region": "Perak", "federal": "Batu Gajah", "state": "Jelapang"},
  {"region": "Perak", "federal": "Batu Gajah", "state": "Menglembu"},
  {"region": "Perak", "federal": "Batu Gajah", "state": "Tronoh"},
  {"region": "Perak", "federal": "Kuala Kangsar", "state": "Bukit Chandan"},
  {"region": "Perak", "federal": "Kuala Kangsar", "state": "Manong"},
  {"region": "Perak", "federal": "Beruas", "state": "Pengkalan Baharu"},
  {"region": "Perak", "federal": "Beruas", "state": "Pantai Remis"},
  {"region": "Perak", "federal": "Beruas", "state": "Astaka"},
  {"region": "Perak", "federal": "Parit", "state": "Belanja"},
  {"region": "Perak", "federal": "Parit", "state": "Bota"},
  {"region": "Perak", "federal": "Kampar", "state": "Malim Nawar"},
  {"region": "Perak", "federal": "Kampar", "state": "Keranji"},
  {"region": "Perak", "federal": "Kampar", "state": "Tulang Sekah"},
  {"region": "Perak", "federal": "Gopeng", "state": "Sungai Rapat"},
  {"region": "Perak", "federal": "Gopeng", "state": "Simpang Pulai"},
  {"region": "Perak", "federal": "Gopeng", "state": "Teja"},
  {"region": "Perak", "federal": "Tapah", "state": "Chenderiang"},
  {"region": "Perak", "federal": "Tapah", "state": "Ayer Kuning"},
  {"region": "Perak", "federal": "Pasir Salak", "state": "Sungai Manik"},
  {"region": "Perak", "federal": "Pasir Salak", "state": "Kampong Gajah"},
  {"region": "Perak", "federal": "Lumut", "state": "Pasir Panjang"},
  {"region": "Perak", "federal": "Lumut", "state": "Pangkor"},
  {"region": "Perak", "federal": "Bagan Datuk", "state": "Rungkup"},
  {"region": "Perak", "federal": "Bagan Datuk", "state": "Hutan Melintang"},
  {"region": "Perak", "federal": "Teluk Intan", "state": "Pasir Bedamar"},
  {"region": "Perak", "federal": "Teluk Intan", "state": "Changkat Jong"},
  {"region": "Perak", "federal": "Tanjong Malim", "state": "Sungkai"},
  {"region": "Perak", "federal": "Tanjong Malim", "state": "Slim"},
  {"region": "Perak", "federal": "Tanjong Malim", "state": "Behrang"},
  {"region": "Pahang", "federal": "Cameron Highlands", "state": "Tanah Rata"},
  {"region": "Pahang", "federal": "Cameron Highlands", "state": "Jelai"},
  {"region": "Pahang", "federal": "Lipis", "state": "Padang Tengku"},
  {"region": "Pahang", "federal": "Lipis", "state": "Cheka"},
  {"region": "Pahang", "federal": "Lipis", "state": "Benta"},
  {"region": "Pahang", "federal": "Raub", "state": "Batu Talam"},
  {"region": "Pahang", "federal": "Raub", "state": "Tras"},
  {"region": "Pahang", "federal": "Raub", "state": "Dong"},
  {"region": "Pahang", "federal": "Jerantut", "state": "Tahan"},
  {"region": "Pahang", "federal": "Jerantut", "state": "Damak"},
  {"region": "Pahang", "federal": "Jerantut", "state": "Pulau Tawar"},
  {"region": "Pahang", "federal": "Indera Mahkota", "state": "Beserah"},
  {"region": "Pahang", "federal": "Indera Mahkota", "state": "Semambu"},
  {"region": "Pahang", "federal": "Kuantan", "state": "Teruntum"},
  {"region": "Pahang", "federal": "Kuantan", "state": "Tanjung Lumpur"},
  {"region": "Pahang", "federal": "Kuantan", "state": "Inderapura"},
  {"region": "Pahang", "federal": "Paya Besar", "state": "Sungai Lembing"},
  {"region": "Pahang", "federal": "Paya Besar", "state": "Lepar"},
  {"region": "Pahang", "federal": "Paya Besar", "state": "Panching"},
  {"region": "Pahang", "federal": "Pekan", "state": "Pulau Manis"},
  {"region": "Pahang", "federal": "Pekan", "state": "Peramu Jaya"},
  {"region": "Pahang", "federal": "Pekan", "state": "Bebar"},
  {"region": "Pahang", "federal": "Pekan", "state": "Chini"},
  {"region": "Pahang", "federal": "Maran", "state": "Luit"},
  {"region": "Pahang", "federal": "Maran", "state": "Kuala Sentul"},
  {"region": "Pahang", "federal": "Maran", "state": "Chenor"},
  {"region": "Pahang", "federal": "Kuala Krau", "state": "Jenderak"},
  {"region": "Pahang", "federal": "Kuala Krau", "state": "Kerdau"},
  {"region": "Pahang", "federal": "Kuala Krau", "state": "Jengka"},
  {"region": "Pahang", "federal": "Temerloh", "state": "Mentakab"},
  {"region": "Pahang", "federal": "Temerloh", "state": "Lanchang"},
  {"region": "Pahang", "federal": "Temerloh", "state": "Kuala Semantan"},
  {"region": "Pahang", "federal": "Bentong", "state": "Bilut"},
  {"region": "Pahang", "federal": "Bentong", "state": "Ketari"},
  {"region": "Pahang", "federal": "Bentong", "state": "Sabai"},
  {"region": "Pahang", "federal": "Bentong", "state": "Pelangai"},
  {"region": "Pahang", "federal": "Bera", "state": "Guai"},
  {"region": "Pahang", "federal": "Bera", "state": "Triang"},
  {"region": "Pahang", "federal": "Bera", "state": "Kemayan"},
  {"region": "Pahang", "federal": "Rompin", "state": "Bukit Ibam"},
  {"region": "Pahang", "federal": "Rompin", "state": "Muadzam Shah"},
  {"region": "Pahang", "federal": "Rompin", "state": "Tioman"},
  {"region": "Selangor", "federal": "Sabak Bernam", "state": "Sungai Air Tawar"},
  {"region": "Selangor", "federal": "Sabak Bernam", "state": "Sabak "},
  {"region": "Selangor", "federal": "Sungai Besar", "state": "Sungai Panjang"},
  {"region": "Selangor", "federal": "Sungai Besar", "state": "Sekinchan "},
  {"region": "Selangor", "federal": "Hulu Selangor", "state": "Hulu Bernam"},
  {"region": "Selangor", "federal": "Hulu Selangor", "state": "Kuala Kubu Baharu"},
  {"region": "Selangor", "federal": "Hulu Selangor", "state": "Batang Kali"},
  {"region": "Selangor", "federal": "Tanjong Karang", "state": "Sungai Burong"},
  {"region": "Selangor", "federal": "Tanjong Karang", "state": " "},
  {"region": "Selangor", "federal": "Kuala Selangor", "state": "Bukit Melawati"},
  {"region": "Selangor", "federal": "Kuala Selangor", "state": "Ijok "},
  {"region": "Selangor", "federal": "Kuala Selangor", "state": "Jeram "},
  {"region": "Selangor", "federal": "Selayang ", "state": "Kuang "},
  {"region": "Selangor", "federal": "Selayang ", "state": "Rawang "},
  {"region": "Selangor", "federal": "Selayang ", "state": "Taman Templer"},
  {"region": "Selangor", "federal": "Gombak ", "state": "Sungai Tua"},
  {"region": "Selangor", "federal": "Gombak ", "state": "Gombak Setia"},
  {"region": "Selangor", "federal": "Gombak ", "state": "Hulu Kelang"},
  {"region": "Selangor", "federal": "Ampang ", "state": "Bukit Antarabangsa"},
  {"region": "Selangor", "federal": "Ampang ", "state": "Lembah Jaya"},
  {"region": "Selangor", "federal": "Pandan ", "state": "Pandan Indah"},
  {"region": "Selangor", "federal": "Pandan ", "state": "Teratai "},
  {"region": "Selangor", "federal": "Hulu Langat", "state": "Dusun Tua"},
  {"region": "Selangor", "federal": "Hulu Langat", "state": "Semenyih "},
  {"region": "Selangor", "federal": "Bangi ", "state": "Kajang "},
  {"region": "Selangor", "federal": "Bangi ", "state": "Sungai Ramal"},
  {"region": "Selangor", "federal": "Bangi ", "state": "Balakong "},
  {"region": "Selangor", "federal": "Puchong ", "state": "Seri Kembangan"},
  {"region": "Selangor", "federal": "Puchong ", "state": "Seri Serdang"},
  {"region": "Selangor", "federal": "Subang ", "state": "Kinrara "},
  {"region": "Selangor", "federal": "Subang ", "state": "Subang Jaya"},
  {"region": "Selangor", "federal": "Petaling Jaya", "state": "Seri Setia "},
  {"region": "Selangor", "federal": "Petaling Jaya", "state": "Taman Medan"},
  {"region": "Selangor", "federal": "Petaling Jaya", "state": "Bukit Gasing"},
  {"region": "Selangor", "federal": "Petaling Jaya", "state": "Kampung Tunku"},
  {"region": "Selangor", "federal": "Damansara", "state": "Bandar Utama"},
  {"region": "Selangor", "federal": "Damansara", "state": "Bukit Lanjan"},
  {"region": "Selangor", "federal": "Sungai Buloh", "state": "Paya Jaras"},
  {"region": "Selangor", "federal": "Sungai Buloh", "state": "Kota Damansara"},
  {"region": "Selangor", "federal": "Shah Alam", "state": "Kota Anggerik"},
  {"region": "Selangor", "federal": "Shah Alam", "state": "Batu Tiga "},
  {"region": "Selangor", "federal": "Kapar ", "state": "Meru "},
  {"region": "Selangor", "federal": "Kapar ", "state": "Sementa "},
  {"region": "Selangor", "federal": "Kapar ", "state": "Selat Klang"},
  {"region": "Selangor", "federal": "Klang ", "state": "Bandar Baru Klang"},
  {"region": "Selangor", "federal": "Klang ", "state": "Pelabuhan Klang"},
  {"region": "Selangor", "federal": "Klang ", "state": " Pandamaran"},
  {"region": "Selangor", "federal": "Kota Raja ", "state": "Sentosa "},
  {"region": "Selangor", "federal": "Kota Raja ", "state": "Sungai Kandis"},
  {"region": "Selangor", "federal": "Kota Raja ", "state": "Kota Kemuning"},
  {"region": "Selangor", "federal": "Kuala Langat", "state": "Sijangkang"},
  {"region": "Selangor", "federal": "Kuala Langat", "state": "Banting "},
  {"region": "Selangor", "federal": "Kuala Langat", "state": "Morib "},
  {"region": "Selangor", "federal": "Sepang ", "state": "Tanjong Sepat"},
  {"region": "Selangor", "federal": "Sepang ", "state": "Dengkil "},
  {"region": "Selangor", "federal": "Sepang ", "state": "Sungai Pelek"},
  {"region": "Federal Territory of Kuala Lumpur", "federal": "Kepong ", "state": " "},
  {"region": "Federal Territory of Kuala Lumpur", "federal": "Batu ", "state": " "},
  {"region": "Federal Territory of Kuala Lumpur", "federal": "Wangsa Maju", "state": " "},
  {"region": "Federal Territory of Kuala Lumpur", "federal": "Bukit Bintang", "state": " "},
  {"region": "Federal Territory of Kuala Lumpur", "federal": "Lembah Pantai", "state": " "},
  {"region": "Federal Territory of Kuala Lumpur", "federal": "Seputeh ", "state": " "},
  {"region": "Federal Territory of Kuala Lumpur", "federal": "Cheras ", "state": " "},
  {"region": "Federal Territory of Kuala Lumpur", "federal": "Bandar Tun Razak", "state": " "},
  {"region": "Federal Territory of Putrajaya", "federal": "Putrajaya ", "state": " "},
  {"region": "Negeri Sembilan", "federal": "Jelebu ", "state": "Chennah "},
  {"region": "Negeri Sembilan", "federal": "Jelebu ", "state": "Pertang "},
  {"region": "Negeri Sembilan", "federal": "Jelebu ", "state": "Sungai Lui "},
  {"region": "Negeri Sembilan", "federal": "Jelebu ", "state": "Klawang "},
  {"region": "Negeri Sembilan", "federal": "Jempol ", "state": "Serting "},
  {"region": "Negeri Sembilan", "federal": "Jempol ", "state": "Palong "},
  {"region": "Negeri Sembilan", "federal": "Jempol ", "state": "Jeram Padang"},
  {"region": "Negeri Sembilan", "federal": "Jempol ", "state": "Bahau "},
  {"region": "Negeri Sembilan", "federal": "Seremban", "state": "Lenggeng "},
  {"region": "Negeri Sembilan", "federal": "Seremban", "state": "Nilai "},
  {"region": "Negeri Sembilan", "federal": "Seremban", "state": "Lobak "},
  {"region": "Negeri Sembilan", "federal": "Seremban", "state": "Temiang "},
  {"region": "Negeri Sembilan", "federal": "Seremban", "state": "Sikamat "},
  {"region": "Negeri Sembilan", "federal": "Seremban", "state": "Ampangan"},
  {"region": "Negeri Sembilan", "federal": "Kuala Pilah", "state": "Juasseh "},
  {"region": "Negeri Sembilan", "federal": "Kuala Pilah", "state": "Seri Menanti"},
  {"region": "Negeri Sembilan", "federal": "Kuala Pilah", "state": "Senaling "},
  {"region": "Negeri Sembilan", "federal": "Kuala Pilah", "state": "Pilah "},
  {"region": "Negeri Sembilan", "federal": "Kuala Pilah", "state": "Johol "},
  {"region": "Negeri Sembilan", "federal": "Rasah ", "state": "Labu "},
  {"region": "Negeri Sembilan", "federal": "Rasah ", "state": "Bukit Kepayang"},
  {"region": "Negeri Sembilan", "federal": "Rasah ", "state": "Rahang "},
  {"region": "Negeri Sembilan", "federal": "Rasah ", "state": "Mambau "},
  {"region": "Negeri Sembilan", "federal": "Rasah ", "state": "Seremban Jaya"},
  {"region": "Negeri Sembilan", "federal": "Rembau ", "state": "Paroi "},
  {"region": "Negeri Sembilan", "federal": "Rembau ", "state": "Chembong"},
  {"region": "Negeri Sembilan", "federal": "Rembau ", "state": "Rantau "},
  {"region": "Negeri Sembilan", "federal": "Rembau ", "state": "Kota "},
  {"region": "Negeri Sembilan", "federal": "Port ", "state": "Chuah "},
  {"region": "Negeri Sembilan", "federal": "Port ", "state": "Lukut "},
  {"region": "Negeri Sembilan", "federal": "Port ", "state": "Bagan Pinang"},
  {"region": "Negeri Sembilan", "federal": "Port ", "state": "Linggi "},
  {"region": "Negeri Sembilan", "federal": "Port ", "state": "Sri Tanjung"},
  {"region": "Negeri Sembilan", "federal": "Tampin ", "state": "Gemas "},
  {"region": "Negeri Sembilan", "federal": "Tampin ", "state": "Gemencheh"},
  {"region": "Negeri Sembilan", "federal": "Tampin ", "state": "Repah "},
  {"region": "Malacca", "federal": "Masjid Tanah", "state": "Kuala Linggi"},
  {"region": "Malacca", "federal": "Masjid Tanah", "state": "Tanjung Bidara"},
  {"region": "Malacca", "federal": "Masjid Tanah", "state": "Ayer Limau"},
  {"region": "Malacca", "federal": "Masjid Tanah", "state": "Lendu "},
  {"region": "Malacca", "federal": "Masjid Tanah", "state": "Taboh Naning"},
  {"region": "Malacca", "federal": "Alor Gajah", "state": "Rembia "},
  {"region": "Malacca", "federal": "Alor Gajah", "state": "Gadek "},
  {"region": "Malacca", "federal": "Alor Gajah", "state": "Machap Jaya"},
  {"region": "Malacca", "federal": "Alor Gajah", "state": "Durian Tunggal"},
  {"region": "Malacca", "federal": "Alor Gajah", "state": "Asahan "},
  {"region": "Malacca", "federal": "Tangga Batu", "state": "Sungai Udang"},
  {"region": "Malacca", "federal": "Tangga Batu", "state": "Pantai Kundor"},
  {"region": "Malacca", "federal": "Tangga Batu", "state": "Paya Rumput"},
  {"region": "Malacca", "federal": "Tangga Batu", "state": "Kelebang "},
  {"region": "Malacca", "federal": "Hang Tuah Jaya", "state": "Pengkalan Batu"},
  {"region": "Malacca", "federal": "Hang Tuah Jaya", "state": "Ayer Keroh"},
  {"region": "Malacca", "federal": "Hang Tuah Jaya", "state": "Bukit Katil "},
  {"region": "Malacca", "federal": "Hang Tuah Jaya", "state": "Ayer Molek"},
  {"region": "Malacca", "federal": "Kota Melaka", "state": "Kesidang "},
  {"region": "Malacca", "federal": "Kota Melaka", "state": "Kota Laksamana"},
  {"region": "Malacca", "federal": "Kota Melaka", "state": "Duyong "},
  {"region": "Malacca", "federal": "Kota Melaka", "state": "Bandar Hilir"},
  {"region": "Malacca", "federal": "Kota Melaka", "state": "Telok Mas "},
  {"region": "Malacca", "federal": "Jasin ", "state": "Bemban "},
  {"region": "Malacca", "federal": "Jasin ", "state": "Rim "},
  {"region": "Malacca", "federal": "Jasin ", "state": "Serkam "},
  {"region": "Malacca", "federal": "Jasin ", "state": "Merlimau "},
  {"region": "Malacca", "federal": "Jasin ", "state": "Sungai Rambai"},
  {"region": "Johor", "federal": "Segamat ", "state": "Buloh Kasap"},
  {"region": "Johor", "federal": "Segamat ", "state": "Jementah "},
  {"region": "Johor", "federal": "Sekijang ", "state": "Pemanis "},
  {"region": "Johor", "federal": "Sekijang ", "state": "Kemelah "},
  {"region": "Johor", "federal": "Labis ", "state": "Tenang "},
  {"region": "Johor", "federal": "Labis ", "state": "Bekok "},
  {"region": "Johor", "federal": "Pagoh ", "state": "Bukit Kepong"},
  {"region": "Johor", "federal": "Pagoh ", "state": "Bukit Pasir "},
  {"region": "Johor", "federal": "Ledang ", "state": "Gambir "},
  {"region": "Johor", "federal": "Ledang ", "state": "Tangkak "},
  {"region": "Johor", "federal": "Ledang ", "state": "Serom "},
  {"region": "Johor", "federal": "Bakri ", "state": "Bentayan "},
  {"region": "Johor", "federal": "Bakri ", "state": "Simpang Jeram"},
  {"region": "Johor", "federal": "Bakri ", "state": "Bukit Naning"},
  {"region": "Johor", "federal": "Muar ", "state": "Maharani "},
  {"region": "Johor", "federal": "Muar ", "state": "Sungai Balang"},
  {"region": "Johor", "federal": "Parit Sulong", "state": "Semerah "},
  {"region": "Johor", "federal": "Parit Sulong", "state": "Sri Medan "},
  {"region": "Johor", "federal": "Ayer Hitam", "state": "Yong Peng"},
  {"region": "Johor", "federal": "Sri Gading", "state": "Semarang "},
  {"region": "Johor", "federal": "Sri Gading", "state": "Parit Yaani"},
  {"region": "Johor", "federal": "Sri Gading", "state": "Parit Raja "},
  {"region": "Johor", "federal": "Batu Pahat", "state": " "},
  {"region": "Johor", "federal": "Batu Pahat", "state": " "},
  {"region": "Johor", "federal": "Batu Pahat", "state": "Rengit "},
  {"region": "Johor", "federal": "Simpang Renggam", "state": "Machap "},
  {"region": "Johor", "federal": "Simpang Renggam", "state": "Layang- Layang"},
  {"region": "Johor", "federal": "Kluang ", "state": "Mengkibol "},
  {"region": "Johor", "federal": "Kluang ", "state": "Mahkota "},
  {"region": "Johor", "federal": "Sembrong", "state": "Paloh "},
  {"region": "Johor", "federal": "Sembrong", "state": "Kahang "},
  {"region": "Johor", "federal": "Mersing ", "state": "Endau "},
  {"region": "Johor", "federal": "Mersing ", "state": "Tenggaroh "},
  {"region": "Johor", "federal": "Tenggara ", "state": "Panti "},
  {"region": "Johor", "federal": "Tenggara ", "state": "Pasir Raja "},
  {"region": "Johor", "federal": "Kota Tinggi", "state": "Sedili "},
  {"region": "Johor", "federal": "Kota Tinggi", "state": "Johor Lama"},
  {"region": "Johor", "federal": "Pengerang", "state": "Penawar "},
  {"region": "Johor", "federal": "Pengerang", "state": "Tanjung Surat"},
  {"region": "Johor", "federal": "Tebrau ", "state": "Tiram "},
  {"region": "Johor", "federal": "Tebrau ", "state": "Puteri Wangsa"},
  {"region": "Johor", "federal": "Pasir Gudang", "state": "Johor Jaya"},
  {"region": "Johor", "federal": "Pasir Gudang", "state": "Permas "},
  {"region": "Johor", "federal": "Johor Bahru", "state": "Larkin "},
  {"region": "Johor", "federal": "Johor Bahru", "state": "Stulang "},
  {"region": "Johor", "federal": "Pulai ", "state": "Perling "},
  {"region": "Johor", "federal": "Pulai ", "state": "Kempas "},
  {"region": "Johor", "federal": "Iskandar Puteri", "state": "Skudai "},
  {"region": "Johor", "federal": "Iskandar Puteri", "state": "Kota Iskandar"},
  {"region": "Johor", "federal": "Kulai ", "state": "Bukit Permai"},
  {"region": "Johor", "federal": "Kulai ", "state": "Bukit Batu "},
  {"region": "Johor", "federal": "Kulai ", "state": "Senai "},
  {"region": "Johor", "federal": "Pontian ", "state": "Benut "},
  {"region": "Johor", "federal": "Pontian ", "state": "Pulai Sebatang"},
  {"region": "Johor", "federal": "Tanjung Piai", "state": "Pekan Nanas"},
  {"region": "Johor", "federal": "Tanjung Piai", "state": "Kukup "},
  {"region": "Federal Territory of Labuan", "federal": "Labuan ", "state": " "},
  {"region": "Sabah", "federal": "Kudat ", "state": "Banggi "},
  {"region": "Sabah", "federal": "Kudat ", "state": "Bengkoka "},
  {"region": "Sabah", "federal": "Kudat ", "state": "Pitas "},
  {"region": "Sabah", "federal": "Kudat ", "state": "Tanjong Kapor"},
  {"region": "Sabah", "federal": "Kota Marudu", "state": " Matunggong"},
  {"region": "Sabah", "federal": "Kota Marudu", "state": "Bandau "},
  {"region": "Sabah", "federal": "Kota Marudu", "state": "Tandek "},
  {"region": "Sabah", "federal": "Kota Belud", "state": "Pintasan "},
  {"region": "Sabah", "federal": "Kota Belud", "state": "Tempasuk "},
  {"region": "Sabah", "federal": "Kota Belud", "state": "Usukan "},
  {"region": "Sabah", "federal": "Kota Belud", "state": "Kadamaian"},
  {"region": "Sabah", "federal": "Tuaran ", "state": "Sulaman "},
  {"region": "Sabah", "federal": "Tuaran ", "state": "Pantai Dalit"},
  {"region": "Sabah", "federal": "Tuaran ", "state": "Tamparuli "},
  {"region": "Sabah", "federal": "Tuaran ", "state": "Kiulu "},
  {"region": "Sabah", "federal": "Sepanggar", "state": "Darau "},
  {"region": "Sabah", "federal": "Sepanggar", "state": "Inanam "},
  {"region": "Sabah", "federal": "Kota Kinabalu", "state": "Likas "},
  {"region": "Sabah", "federal": "Kota Kinabalu", "state": "Api-Api "},
  {"region": "Sabah", "federal": "Kota Kinabalu", "state": "Luyang "},
  {"region": "Sabah", "federal": "Putatan ", "state": "Tanjong Aru"},
  {"region": "Sabah", "federal": "Putatan ", "state": "Petagas "},
  {"region": "Sabah", "federal": "Putatan ", "state": "Tanjung Keramat"},
  {"region": "Sabah", "federal": "Penampang", "state": "Kapayan "},
  {"region": "Sabah", "federal": "Penampang", "state": "Moyog "},
  {"region": "Sabah", "federal": "Papar ", "state": "Limbahau "},
  {"region": "Sabah", "federal": "Papar ", "state": "Kawang "},
  {"region": "Sabah", "federal": "Papar ", "state": "Pantai Manis"},
  {"region": "Sabah", "federal": "Kimanis ", "state": "Bongawan "},
  {"region": "Sabah", "federal": "Kimanis ", "state": "Membakut "},
  {"region": "Sabah", "federal": "Beaufort ", "state": "Klias "},
  {"region": "Sabah", "federal": "Beaufort ", "state": "Kuala Penyu"},
  {"region": "Sabah", "federal": "Sipitang ", "state": "Lumadan "},
  {"region": "Sabah", "federal": "Sipitang ", "state": "Sindumin "},
  {"region": "Sabah", "federal": "Ranau ", "state": "Kundasang"},
  {"region": "Sabah", "federal": "Ranau ", "state": "Karanaan "},
  {"region": "Sabah", "federal": "Ranau ", "state": "Paginatan "},
  {"region": "Sabah", "federal": "Keningau ", "state": "Tambunan "},
  {"region": "Sabah", "federal": "Keningau ", "state": "Bingkor "},
  {"region": "Sabah", "federal": "Keningau ", "state": "Liawan "},
  {"region": "Sabah", "federal": "Tenom ", "state": "Melalap "},
  {"region": "Sabah", "federal": "Tenom ", "state": "Kemabong"},
  {"region": "Sabah", "federal": "Pensiangan", "state": "Tulid "},
  {"region": "Sabah", "federal": "Pensiangan", "state": "Sook "},
  {"region": "Sabah", "federal": "Pensiangan", "state": "Nabawan "},
  {"region": "Sabah", "federal": "Beluran ", "state": "Telupid "},
  {"region": "Sabah", "federal": "Beluran ", "state": "Sugut "},
  {"region": "Sabah", "federal": "Beluran ", "state": "Labuk "},
  {"region": "Sabah", "federal": "Libaran ", "state": "Gum-Gum "},
  {"region": "Sabah", "federal": "Libaran ", "state": "Sungai Manila"},
  {"region": "Sabah", "federal": "Libaran ", "state": "Sungai Sibuga"},
  {"region": "Sabah", "federal": "Batu Sapi ", "state": "Sekong "},
  {"region": "Sabah", "federal": "Batu Sapi ", "state": "Karamunting"},
  {"region": "Sabah", "federal": "Sandakan", "state": "Elopura "},
  {"region": "Sabah", "federal": "Sandakan", "state": "Tanjong Papat"},
  {"region": "Sabah", "federal": "Kinabatangan", "state": "Kuamut "},
  {"region": "Sabah", "federal": "Kinabatangan", "state": "Lamag "},
  {"region": "Sabah", "federal": "Kinabatangan", "state": "Sukau "},
  {"region": "Sabah", "federal": "Lahad Datu", "state": "Tungku "},
  {"region": "Sabah", "federal": "Lahad Datu", "state": "Segama "},
  {"region": "Sabah", "federal": "Lahad Datu", "state": "Silam "},
  {"region": "Sabah", "federal": "Lahad Datu", "state": "Kunak "},
  {"region": "Sabah", "federal": "Semporna", "state": "Sulabayan "},
  {"region": "Sabah", "federal": "Semporna", "state": "Senallang "},
  {"region": "Sabah", "federal": "Semporna", "state": "Bugaya "},
  {"region": "Sabah", "federal": "Tawau ", "state": "Balung "},
  {"region": "Sabah", "federal": "Tawau ", "state": "Apas "},
  {"region": "Sabah", "federal": "Tawau ", "state": "Sri Tanjong"},
  {"region": "Sabah", "federal": "Kalabakan", "state": "Kukusan "},
  {"region": "Sabah", "federal": "Kalabakan", "state": "Tanjong Batu"},
  {"region": "Sabah", "federal": "Kalabakan", "state": "Merotai "},
  {"region": "Sabah", "federal": "Kalabakan", "state": "Sebatik "},
  {"region": "Sarawak", "federal": "Mas Gading", "state": "Opar "},
  {"region": "Sarawak", "federal": "Mas Gading", "state": "Tasik Biru "},
  {"region": "Sarawak", "federal": "Santubong", "state": "Tanjong Datu"},
  {"region": "Sarawak", "federal": "Santubong", "state": "Pantai Damai"},
  {"region": "Sarawak", "federal": "Santubong", "state": "Demak Laut"},
  {"region": "Sarawak", "federal": "Petra Jaya", "state": "Tupong "},
  {"region": "Sarawak", "federal": "Petra Jaya", "state": "Samariang"},
  {"region": "Sarawak", "federal": "Petra Jaya", "state": "Satok "},
  {"region": "Sarawak", "federal": "Bandar Kuching", "state": "Padungan "},
  {"region": "Sarawak", "federal": "Bandar Kuching", "state": "Pending "},
  {"region": "Sarawak", "federal": "Bandar Kuching", "state": "Batu Lintang"},
  {"region": "Sarawak", "federal": "Stampin ", "state": "Kota Sentosa"},
  {"region": "Sarawak", "federal": "Stampin ", "state": "Batu Kitang"},
  {"region": "Sarawak", "federal": "Stampin ", "state": "Batu Kawah"},
  {"region": "Sarawak", "federal": "Kota Samarahan", "state": "Asajaya "},
  {"region": "Sarawak", "federal": "Kota Samarahan", "state": "Muara Tuang"},
  {"region": "Sarawak", "federal": "Kota Samarahan", "state": "Stakan "},
  {"region": "Sarawak", "federal": "Puncak Borneo", "state": "Serembu "},
  {"region": "Sarawak", "federal": "Puncak Borneo", "state": "Mambong "},
  {"region": "Sarawak", "federal": "Puncak Borneo", "state": "Tarat "},
  {"region": "Sarawak", "federal": "Serian ", "state": "Tebedu "},
  {"region": "Sarawak", "federal": "Serian ", "state": "Kedup "},
  {"region": "Sarawak", "federal": "Serian ", "state": "Bukit Semuja"},
  {"region": "Sarawak", "federal": "Batang Sadong", "state": "Sadong Jaya"},
  {"region": "Sarawak", "federal": "Batang Sadong", "state": "Simunjan "},
  {"region": "Sarawak", "federal": "Batang Sadong", "state": "Gedong "},
  {"region": "Sarawak", "federal": "Batang Lupar", "state": "Sebuyau "},
  {"region": "Sarawak", "federal": "Batang Lupar", "state": "Lingga "},
  {"region": "Sarawak", "federal": "Batang Lupar", "state": "Beting Maro"},
  {"region": "Sarawak", "federal": "Sri Aman ", "state": "Balai Ringin"},
  {"region": "Sarawak", "federal": "Sri Aman ", "state": "Bukit Begunan"},
  {"region": "Sarawak", "federal": "Sri Aman ", "state": "Simanggang"},
  {"region": "Sarawak", "federal": "Lubok Antu", "state": "Engkilili "},
  {"region": "Sarawak", "federal": "Lubok Antu", "state": "Batang Ai "},
  {"region": "Sarawak", "federal": "Betong ", "state": "Saribas "},
  {"region": "Sarawak", "federal": "Betong ", "state": "Layar "},
  {"region": "Sarawak", "federal": "Betong ", "state": "Bukit Saban"},
  {"region": "Sarawak", "federal": "Saratok ", "state": "Kalaka "},
  {"region": "Sarawak", "federal": "Saratok ", "state": "Krian "},
  {"region": "Sarawak", "federal": "Saratok ", "state": "Kabong "},
  {"region": "Sarawak", "federal": "Tanjong Manis", "state": "Kuala Rajang"},
  {"region": "Sarawak", "federal": "Tanjong Manis", "state": "Semop "},
  {"region": "Sarawak", "federal": "Igan ", "state": "Daro "},
  {"region": "Sarawak", "federal": "Igan ", "state": "Jemoreng "},
  {"region": "Sarawak", "federal": "Sarikei ", "state": "Repok "},
  {"region": "Sarawak", "federal": "Sarikei ", "state": "Meradong "},
  {"region": "Sarawak", "federal": "Julau ", "state": "Pakan "},
  {"region": "Sarawak", "federal": "Julau ", "state": "Meluan "},
  {"region": "Sarawak", "federal": "Kanowit ", "state": "Ngemah "},
  {"region": "Sarawak", "federal": "Kanowit ", "state": "Machan "},
  {"region": "Sarawak", "federal": "Lanang ", "state": "Bukit Assek"},
  {"region": "Sarawak", "federal": "Lanang ", "state": "Dudong "},
  {"region": "Sarawak", "federal": "Sibu ", "state": "Bawang Assan"},
  {"region": "Sarawak", "federal": "Sibu ", "state": "Pelawan "},
  {"region": "Sarawak", "federal": "Sibu ", "state": "Nangka "},
  {"region": "Sarawak", "federal": "Mukah ", "state": "Dalat "},
  {"region": "Sarawak", "federal": "Mukah ", "state": "Tellian "},
  {"region": "Sarawak", "federal": "Mukah ", "state": "Balingian "},
  {"region": "Sarawak", "federal": "Selangau ", "state": "Tamin "},
  {"region": "Sarawak", "federal": "Selangau ", "state": "Kakus "},
  {"region": "Sarawak", "federal": "Kapit ", "state": "Pelagus "},
  {"region": "Sarawak", "federal": "Kapit ", "state": "Katibas "},
  {"region": "Sarawak", "federal": "Kapit ", "state": "Bukit Goram"},
  {"region": "Sarawak", "federal": "Hulu Rajang", "state": "Baleh "},
  {"region": "Sarawak", "federal": "Hulu Rajang", "state": "Belaga "},
  {"region": "Sarawak", "federal": "Hulu Rajang", "state": "Murum "},
  {"region": "Sarawak", "federal": "Bintulu ", "state": "Jepak "},
  {"region": "Sarawak", "federal": "Bintulu ", "state": "Tanjong Batu"},
  {"region": "Sarawak", "federal": "Bintulu ", "state": "Kemena "},
  {"region": "Sarawak", "federal": "Bintulu ", "state": "Samalaju "},
  {"region": "Sarawak", "federal": "Sibuti ", "state": "Bekenu "},
  {"region": "Sarawak", "federal": "Sibuti ", "state": "Lambir "},
  {"region": "Sarawak", "federal": "Miri ", "state": "Piasau "},
  {"region": "Sarawak", "federal": "Miri ", "state": "Pujut "},
  {"region": "Sarawak", "federal": "Miri ", "state": "Senadin "},
  {"region": "Sarawak", "federal": "Baram ", "state": "Marudi "},
  {"region": "Sarawak", "federal": "Baram ", "state": "Telang Usan"},
  {"region": "Sarawak", "federal": "Baram ", "state": "Mulu "},
  {"region": "Sarawak", "federal": "Limbang ", "state": "Bukit Kota "},
  {"region": "Sarawak", "federal": "Limbang ", "state": "Batu Danau"},
  {"region": "Sarawak", "federal": "Lawas ", "state": "Ba'kelalan "},
  {"region": "Sarawak", "federal": "Lawas ", "state": "Bukit Sari "}
];
